# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Arash Ghoreyshi
tagline:          'blog'
description:      'gang star fashion killa'
url:              http://greyshi.com
timezone: US/Pacific

author:
  name:           'Arash Ghoreyshi'
  url:            https://twitter.com/ashgreyshi

# Gems
gems: [jekyll-paginate]

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/greyshi
