# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Arash Ghoreyshi
tagline:          'blog'
description:      'gang star fashion killa'
url:              http://greyshi.com
timezone: America/Chicago

author:
  name:           'Arash Ghoreyshi'
  url:            https://twitter.com/ashgreyshi

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/greyshi
